apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-backend-svc
                port:
                  number: 8080
      host: aba8887fc911c43a7bb1d964c1bb3840-1202117864.us-east-1.elb.amazonaws.com
