apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
data:
  PASSWORD: MTIzNDU2Nzg=  # base64 encoded value of "123"
  DB_USERNAME: cm9vdA==     # base64 encoded value of "root" echo -n "root" | base64
